[font]
size=18

[[keyboard.bindings]]
key='Return'
mods='Control'
action='SpawnNewInstance'

[[keyboard.bindings]]
key='E'
mods='Control'
action='Down'
mode='Vi'
[[keyboard.bindings]]
key='E'
mods='Control'
action='Down'
mode='Vi'
[[keyboard.bindings]]
key='E'
mods='Control'
action='Down'
mode='Vi'
[[keyboard.bindings]]
key='E'
mods='Control'
action='Down'
mode='Vi'
[[keyboard.bindings]]
key='E'
mods='Control'
action='Down'
mode='Vi'

[[keyboard.bindings]]
key='Y'
mods='Control'
action='Up'
mode='Vi'
[[keyboard.bindings]]
key='Y'
mods='Control'
action='Up'
mode='Vi'
[[keyboard.bindings]]
key='Y'
mods='Control'
action='Up'
mode='Vi'
[[keyboard.bindings]]
key='Y'
mods='Control'
action='Up'
mode='Vi'
[[keyboard.bindings]]
key='Y'
mods='Control'
action='Up'
mode='Vi'
